POST http://localhost:1000/videos
Content-Type: application/json

{
   "title": "vídeo 01",
   "description": "Essse é o primeiro vídeo",
   "duration": 320
}

###

GET http://localhost:1000/videos

###

PUT http://localhost:1000/videos/aa17630f-61b3-42af-b44e-496d8634d145
Content-Type: application/json

{
   "title": "vídeo node with postgres",
   "description": "This video is about node",
   "duration": 250
}

###

DELETE http://localhost:1000/videos/8ec3a6fd-c992-4ee2-9abc-15f3bce0f589